application/admin/views.py
"""
Admin: Sub-module
========================

Manages the admin views, handling data preparation
and presentation of Track and Genre data.

Views:

    manage_genres()

    manage_tracks()


Functions:

    add_genre()

    delete_genre()
"""


from flask import (Blueprint, render_template, redirect,
                   url_for, session, flash, request)
from application.tracks.classes import Track


# Initialize admin blueprint
admin = Blueprint('admin', __name__)


@admin.route("/manage-genres")
def manage_genres():
    """
    Manage genres view

    Queries mongoDB Genre collection for all genres,
    which are passed in to the render_template return
    function, to be rendered onto the 'manage-genres.html'

    View only displayed if user 'admin' is logged in.
    """

    if not session.get("user") is None:

        # Avoids display of page if any user other than
        # admin attempts to manually enter URL path
        if session["user"] == "admin":

            all_genres = Track.get_genres()
            return render_template('manage-genres.html', all_genres=all_genres)

        else:
            flash("You're not meant to be there!")
            return redirect(url_for('main.index'))

    else:
        flash("You're not meant to be there!")
        return redirect(url_for("main.index"))


@admin.route("/add-genre", methods=["GET", "POST"])
def add_genre():
    """
    Add Genre Function

    Handles form input in 'manage_genres' view, and
    inserts new genre data into mongoDB 'Genre'
    collection.
    """

    if request.method == "POST":

        genre_name = request.form.get("genre_name")

        if genre_name != '':

            genre_data = {
                "genre_name": genre_name
            }

            try:
                Track.add_genre(genre_data)
                flash("Genre added successfully")
                return redirect(url_for("admin.manage_genres"))

            except:
                flash("Something went wrong. Please try again")
                return redirect(url_for("admin.manage_genres"))

        else:
            flash("No genre name given")
            return redirect(url_for("admin.manage_genres"))


@admin.route("/delete-genre/<genre_id>")
def delete_genre(genre_id):
    """
    Delete Genre View

    Queries mongoDB Genre collection and deletes
    Genre, using genre_id as the argument.
    """

    if session["user"] == "admin":

        try:
            Track.delete_genre(genre_id)
            flash("Genre deleted successfully")
            return redirect(url_for("admin.manage_genres"))
        except:
            flash("Something went wrong. Please try again")
            return redirect(url_for("admin.manage_genres"))


@admin.route("/manage-tracks")
def manage_tracks():

    if not session.get("user") is None:

        if session["user"] == "admin":

            all_tracks = Track.get_all_tracks()
            all_genres = Track.get_genres()

            return render_template("manage-tracks.html", all_tracks=all_tracks,
                                   all_genres=all_genres)

        else:
            flash("You're not meant to be there!")
            return redirect(url_for('main.index'))

    else:
        flash("You're not meant to be there!")
        return redirect(url_for('main.index'))

application/main/views.py
"""
Main: Sub-module

Handles views for Home Page and Contact Page

Handles data from form input in Contact Page
and sends email to website owner.

Views:
    index()

    contact()

Functions:
    send_email()
"""


from flask import render_template, url_for, Blueprint, request, flash, redirect
from application import mailing
from flask_mail import Message
import os

# Initialize 'main' blueprint
main = Blueprint("main", __name__)


@main.route("/")
@main.route("/index")
def index():
    """
    Renders the website's home page.
    """
    return render_template("index.html")


@main.route("/contact", methods=["GET", "POST"])
def contact():
    """
    Renders the website's contact page.
    """
    return render_template("contact.html")


@main.route("/send_email", methods=["GET", "POST"])
def send_email():
    """
    Handles data submitted from form in
    Contact page. Flask Mail utilised
    to send email to website owner, in
    html format ("contact-message.html")
    """
    if request.method == "POST":

        sender = request.form.get("full_name")
        sender_email = request.form.get("email_address")
        message = request.form.get("questions_comments")

        msg = Message()
        msg.subject = "Cross//Tracks Feedback/Query"
        msg.sender = sender_email
        msg.recipients = ['o.cadman@live.co.uk']
        msg.html = render_template('contact-message.html',
                                   user='Oliver', sender_name=sender,
                                   sender_email=sender_email, message=message)

        try:
            mailing.send(msg)
            flash("Thanks for contacting us! We will reply shortly")
            return redirect(url_for('main.contact'))
        except:
            flash('Sorry, something went wrong. Please try again')
            return redirect(url_for('main.contact'))

application/users/views.py
"""
User: Sub-module
==========

Sub-module to handle routes and data relating
to users.

Views:
    build_profile()

    login()

    user_profile()


Functions:

    register_user()

    edit_profile()

    logout()

    display_profile_image()

    edit_profile_img()

    delete_profile()
"""

import os

from flask import (Blueprint, render_template,
                   url_for, flash, redirect, request,
                   session, abort)
from application.users.classes import User
from application.tracks.classes import Track
from application.comments.classes import Comment
from application import Config
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from werkzeug.datastructures import FileStorage
from application.helpers.users import calculate_user_age
from application import mongo
from bson.objectid import ObjectId
from time import time
from flask_mail import Message
from application import mailing
from urllib.parse import urlparse

from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
if os.path.exists("env.py"):
    import env


# Initialize users blueprint
users = Blueprint('users', __name__)


@users.route("/register", methods=["GET", "POST"])
def register_user():
    """
    Renders "register.html" template

    Handles data submitted through form in
    Register page

    Checks if the submitted username already
    exists in the database.

    Uses password validation to ensure the
    password is in the correct format, and
    that the first password matches the
    confirmed password.

    If all checks are passed, a new User
    object is instantiated and registered,
    and a session cookie is created, assigned
    to the username provided in registration
    form.
    """

    if request.method == "POST":

        username = request.form.get("username").lower()
        password = request.form.get("password")
        confirm_password = request.form.get("confirm_password")
        email_address = request.form.get("email_address")

        if not User.validate_password_match(password,
                                            confirm_password):
            flash("Passwords do not match")
            return redirect(request.referrer)

        if not User.validate_password_format(password):
            flash("Password format invalid")
            return redirect(request.referrer)

        if User.find_user_by_username(username):
            flash("Username already exists")
            return redirect(request.referrer)

        if User.find_user_by_email(email_address):
            flash("Email already exists")
            return redirect(request.referrer)

        new_user = User(username, password, email_address)

        new_user.register()
        flash("Registration Successful")
        session["user"] = request.form.get("username").lower()

        return redirect(url_for('users.build_profile',
                                username=session["user"]))

    return render_template('register.html')


@users.route("/profile-edit/<username>", methods=["GET", "POST"])
def build_profile(username):
    """
    Renders "build-profile.html"

    Runs after initial registration, and handles form
    data submitted in Build Profile page.

    If the user selects a profile image, methods in
    User class are used to validate file format and
    size. If all checks are passed, the file is saved
    to mongodb fs.files and fs.chunks collections.

    Dictionary is made containing data submitted through
    form, and passed into User class' static method
    "complete_user_profile()"
    """

    if request.method == "POST":

        if 'profile_image' in request.files:

            profile_image = request.files['profile_image']

            if profile_image.filename != '':

                allowed_filesize = User.check_image_filesize(
                                        request.cookies.get('filesize'))
                if not allowed_filesize:
                    flash('Your file is too large!')
                    return redirect(url_for("users.build_profile",
                                            username=session["user"]))

                allowed_image = User.allowed_file(profile_image.filename)

                if not allowed_image:
                    flash(("Images can have extensions 'jpg'",
                           "'jpeg', 'gif', 'png' and 'pdf' only."))
                    return redirect(url_for('users.build_profile',
                                    username=username))

                else:
                    mongo.save_file(profile_image.filename, profile_image)

            profile_info = {
                "first_name": request.form.get("first_name"),
                "last_name": request.form.get("last_name"),
                "date_of_birth": request.form.get("date_of_birth"),
                "city": request.form.get("city"),
                "country": request.form.get("country"),
                "about_user": request.form.get("about_user"),
                "is_artist": request.form.get("is_artist"),
                "profile_image": profile_image.filename
                }

            try:
                User.complete_user_profile(username, profile_info)
                flash("Thanks. We hope you enjoy Cross//Tracks!")
                return redirect(url_for("users.user_profile",
                                        username=username))
            except:
                flash("Sorry, something went wrong, please try again.")
                return redirect(url_for("users.build_profile"))

    return render_template('build-profile.html')


@users.route("/login", methods=["GET", "POST"])
def login():
    """
    Renders "login.html"

    Handles data submitted from login form.

    Finds username in "users" collection.

    Checks that the password matches the
    password hash held in the user document
    in "users" collection.

    If all checks are passed, session cookie
    is created and assigned to username, and
    user is redirected to the home page, with
    welcome message.
    """

    if request.method == "POST":
        login_username = request.form.get("username").lower()
        login_password = request.form.get("password")

        user = User.find_user_by_username(login_username.lower())
        if user:
            password_check = User.check_password(
                             user["password"],
                             login_password)
            if password_check:
                session["user"] = login_username

                flash("Welcome back, {}".format(login_username))
                return redirect(url_for('main.index'))

            else:
                flash("Invalid username/password")
                return redirect(request.referrer)
        else:
            flash("Invalid username/password")
            return redirect(request.referrer)

    # Flash message to give feedback to user if they
    # attempt to like a track without logging in.
    parsed_url = urlparse(request.referrer)

    if parsed_url.path == '/browse-tracks':
        flash('Please login to like tracks!')
    return render_template("login.html")


@users.route("/edit-profile/<username>", methods=["GET", "POST"])
def edit_profile(username):
    """
    Handles data submitted from form in modal,
    in User Profile page.

    Organises submitted data into dictionary,
    and passed into User class' "edit_profile()"
    method, to updated relative user document in
    mongoDB "users" collection.
    """

    if request.method == "POST":

        if not username:
            flash("You need to be logged in to edit your profile")
            return redirect("users.login")

        is_artist = "on" if request.form.get("is_artist") else "off"

        edited_info = {
            "first_name": request.form.get("first_name"),
            "last_name": request.form.get("last_name"),
            "date_of_birth": request.form.get("date_of_birth"),
            "city": request.form.get("city"),
            "country": request.form.get("country"),
            "about_user": request.form.get("about_user"),
            "is_artist": is_artist
        }

        try:
            User.edit_profile(username, edited_info)
            flash("Your profile has been updated")
            return redirect(url_for("users.user_profile",
                                    username=session["user"]))
        except:
            flash("Sorry, something went wrong. Please try again.")
            return redirect(url_for("users.user_profile",
                                    username=session["user"]))


@users.route("/logout")
def logout():
    """
    If user is logged in:

    Removes "user" session cookie, and
    logs user out, redirecting to website's
    home page.

    If user is already logged out, appropriate
    flash message is displayed.
    """

    # Custom error handling in the case that
    # the user is already logged out.
    if session.get("user"):
        session.pop("user")
        flash("You have been logged out")
        return redirect(url_for("main.index"))
    else:
        flash("You are already logged out!")
        return redirect(url_for("main.index"))


@users.route("/file/<path:filename>")
def display_profile_image(filename):
    """
    Queries mongoDB fs.files collection using
    filename to match file, and sends profile image
    to client, which is returned to be displayed
    in User Profile page, and on Track cards/modals
    in Browse Tracks page.
    """

    try:
        profile_image = mongo.send_file(filename)
        return profile_image
    except Exception as e:
        print(f"Error uploading image: {e}")
        return None


@users.route("/user-profile/<username>")
def user_profile(username):
    """
    Invokes function to query MongoDB user collection
    by username in URL parameter. Displays user's details
    collected in build_profile function, as well as
    user's tracks.

application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block meta %}
    {% endblock %}
    <!--FontAwesome CDN-->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
         type="text/css">
    <!--MaterializeCSS CDN-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <!-- Favicon -->
    <link rel="shortcut icon" href="{{url_for('static', filename='images/favicon/favicon.ico')}}">
    <title>Cross//Tracks</title>
</head>
<body>
    <!-- Dropdown Menu for Account Links -->
    <ul id="account-dropdown-desktop" class="dropdown-content">
        <li><a href="{{url_for('users.user_profile', username=session['user'])}}">My Profile</a></li>
        <li class="divider"></li>
        <li><a href="{{url_for('users.logout')}}">Logout</a></li>
    </ul>
    <!--Navbar for Laptop/Desktop devices-->
    <div class="navbar-fixed">
        <nav class="nav-extended">
            <div class="nav-wrapper browser-default">
                <a href="{{url_for('main.index')}}" class="brand-logo">
                    Cross//Tracks
                </a>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="fas fa-bars"></i></a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li>
                        <a href="{{url_for('main.index')}}">Home</a>
                    </li>
                    <li>
                        <a href="{{url_for('tracks.browse_tracks')}}">Browse All Tracks</a>
                    </li>
                    {% if session.user %}
                    <li>
                        <a href="{{url_for('tracks.add_track', username=session['user'])}}">Add A Track</a>
                    </li>
                    {% endif %}
                    {% if not session.user %}
                    <li>
                        <a href="{{url_for('users.register_user')}}" class="modal-trigger">Register</a>
                    </li>
                    <li>
                        <a href="{{url_for('users.login')}}">Login</a>
                    </li>
                    {% endif %}
                    {% if session.user %}
                    <li>
                        <a class="dropdown-trigger" href="#!" data-target="account-dropdown-desktop">My Account</a>
                    </li>
                    {% endif %}
                     {% if session.user|lower == "admin"|lower %}
                     <!-- Links for Admin -->
                     <li>
                         <a href="{{url_for('admin.manage_genres')}}">Manage Genres</a>
                     </li>
                     <li>
                         <a href="{{url_for('admin.manage_tracks')}}">Manage Tracks</a>
                     </li>
                     {% endif %}
    
                </ul>
            </div>
             </nav>
    </div>
        <!--Navbar for Mobile Devices -->
        <ul id="mobile-demo" class="sidenav">
            <li>
                <a href="{{url_for('main.index')}}">Home</a>
            </li>
            <li>
                <a href="{{url_for('tracks.browse_tracks')}}">Browse All Tracks</a>
            </li>
            {% if session.user %}
            <li>
                <a href="{{url_for('tracks.add_track', username=session['user'])}}">Add A Track</a>
            </li>
            {% endif %}
            {% if not session.user %}
            <li>
                <a href="{{url_for('users.register_user')}}" class="modal-trigger">Register</a>
            </li>
            <li>
                <a href="{{url_for('users.login')}}">Login</a>
            </li>
            {% endif %}
            {% if session.user %}
            <li>
                <a class="dropdown-trigger" href="#!" data-target="account-dropdown-mobile">My Account</a>
            </li>
            {% endif %}
            {% if session.user|lower == "admin"|lower %}
            <!-- Links for Admin -->
             <li>
                 <a href="{{url_for('admin.manage_genres')}}">Manage Genres</a>
             </li>
             <li>
                 <a href="{{url_for('admin.manage_tracks')}}">Manage Tracks</a>
             </li>
            {% endif %}
        </ul>
      <!-- Dropdown for logged in users -->
        <ul id="account-dropdown-mobile" class="dropdown-content">
            <li><a href="{{url_for('users.user_profile', username=session['user'])}}">My Profile</a></li>
            <li class="divider"></li>
            <li><a href="{{url_for('users.logout')}}">Logout</a></li>
        </ul>
    <main>
            <!-- All other page content -->
            {% block content %}
            {% endblock %}
    </main>
    <!-- Footer -->
    <footer class="page-footer">
        <div class="container">
            <div class="row center-align">
                {% if not session.user %}
                <div class="col s4">
                    <ul class="domestic-links">
                        <li><a href="{{url_for('users.register_user')}}">Register</a></li>
                    </ul>
                </div>
                <div class="col s4">
                    <ul class="domestic-links">
                        <li><a href="{{url_for('users.login')}}">Login</a></li>
                    </ul>
                </div>
                <div class="col s4">
                    <ul class="domestic-links">
                        <li><a href="{{url_for('main.contact')}}">Contact</a></li>
                    </ul>
                </div>
                {% else %}
                 <div class="col s6">
                     <ul class="domestic-links">
                         <li><a href="{{url_for('users.logout')}}">Logout</a></li>
                     </ul>
                 </div>
                 <div class="col s6">
                     <ul class="domestic-links">
                         <li><a href="{{url_for('main.contact')}}">Contact</a></li>
                     </ul>
                 </div>
                {% endif %}
            </div>
            <div class="row social-links-row center-align">
                <div class="col s12">
                    <ul class="social-links">
                        <li><a href="https://www.spotify.com" target="_blank" rel="noopener"><i class="fab fa-spotify"></i></a></li>
                        <li><a href="https://www.github.com/OliverCadman" target="_blank" rel="noopener"><i
                                    class="fab fa-github"></i></a></li>
                        <li><a href="https://www.soundcloud.com" target="_blank" rel="noopener"><i
                                    class="fab fa-soundcloud"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!--jQuery-->
   <script src="https://code.jquery.com/jquery-3.6.0.min.js"
       integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!--MaterializeCSS JavaScript-->
    <script src="{{url_for('static', filename='js/initialization.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{{url_for('static', filename='js/toast.js')}}"></script>

    <!-- Flash Messages displayed through Materialize 'toasts'-->
    <!-- displayToast() function found in toast.js file -->
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <script>
            displayToast({{ messages | tojson | safe}});
        </script>

    {% endif %}
    {% endwith %}
    <!-- Scripts for other pages -->
    {% block scripts %}
    {% endblock %}
</body>

</html>

application/templates/contact-message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cross//Tracks Email</title>
</head>
<body>
   <p>Dear {{user}}</p>
   <p>You have received an email from {{sender_name}}:</p>
   <p>{{message}}</p>
   <p>You can respond to the sender at {{sender_email}}</p>
   <p>Thanks, best wishes</p>
</body>
</html>

application/templates/contact.html
{% extends "base.html" %}
{% block meta %}
<meta name="description" content="Cross//Tracks, track sharing website. Contact Page">
<meta name="keywords" content="Cross//Tracks, contact, contact form, email">
<meta name="author" content="Oliver Cadman">
{% endblock %}
{% block content %}
<section>
    <div class="contact-body">
        <div class="row">
            <!-- Contact Header -->
            <div class="col s12">
            <div class="contact-header">
                    <h1>Contact</h1>
                </div>
            </div>
        </div>
        <div class="row contact-lead-container">
            <div class="col s12">
                <!-- Vector Graphic -->
                <div class="contact-vector-wrapper">
                    <figure>
                        <img src="{{url_for('static', filename='images/contact-vector.png')}}" class="contact-vector" 
                        alt="Vector graphic for contact page">
                    </figure>
                </div>
                <div class="contact-lead">
                    <p>We're always looking to improve your Cross//Tracks experience.</p>
                    <p>If you have any questions or comments about Cross//Tracks, we would love to hear from you!</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <!-- Contact Form -->
                <div class="contact-form-wrapper">
                <form action="{{url_for('main.send_email')}}" method="POST" class="contact-form card-panel">
                        <div class="input-field">
                            <input type="text" name="full_name" id="full_name" required>
                            <label for="full_name">Please enter your name</label>
                        </div>
                        <div class="input-field">
                            <input type="email" name="email_address" id="email_address" required>
                            <label for="email_address">Please enter your email address</label>
                        </div>
                        <div class="input-field">
                            <textarea name="questions_comments" id="questions_comments" cols="30" rows="10" class="materialize-textarea" required></textarea>
                            <label for="questions_comments">Let us know what you think!</label>
                        </div>
                        <div class="submit-btn">
                            <button type="submit" class="btn">Send Email</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

application/templates/manage-genres.html
{% extends "base.html" %}
{% block meta %}
<meta name="description" content="Cross//Tracks, track sharing website. Manage Genres Page">
<meta name="keywords" content="Cross//Tracks, admin, manage genres, edit">
<meta name="author" content="Oliver Cadman">
{% endblock %}
{% block content %}
    <div class="manage-genre-container">
        <h1>Manage Genres</h1>
        <div class="container">
            <div class="row">
                <div class="col s12 z-depth-5 delete-genre-wrapper">
                    <h2 class="center-align">Delete a Genre</h2>
                    {% if all_genres %}
                    {% for genre in all_genres %}
                    <div class="chip genre-chip">
                        {{ genre.genre_name }}
                        <a href="#remove_genre_modal_{{genre._id}}" class="modal-trigger">
                            <i class="fas fa-times-circle remove-genre"></i>
                        </a>
                    </div>
                    <div class="modal delete-genre-modal" id="remove_genre_modal_{{genre._id}}">
                        <i class="fas fa-times-circle modal-close close-modal-icon" data-group="close-modal"></i>
                        <div class="modal-content">
                            <div class="row">
                                <div class="col s12 confirm-delete-container">
                                    <div class="confirm-delete-message center-align">
                                        <p>Deleting {{genre.genre_name}}</p>
                                    </div>
                                    <div class="confirm-delete-wrapper center-align">
                                        <p>Are you sure you want to continue?</p>
                                        <a href="{{url_for('admin.delete_genre', genre_id=genre._id)}}"
                                            class="btn delete-track-btn">Delete</a>
                                        <button type="button" class="btn modal-close cancel-delete-btn">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="row add-genre-container">
                     <div class="col s12 m6 add-genre-wrapper z-depth-5">
                         <h3 class="center-align">
                             Add a Genre
                         </h3>
                         <div class="add-genre-form-wrapper">
                             <form action="{{url_for('admin.add_genre')}}" method="POST"
                             class="add-genre-form">
                                 <div class="input-field">
                                     <input type="text" name="genre_name" id="genre_name">
                                     <label for="genre_name">Genre Name</label>
                                 </div>
                                 <div class="submit-btn">
                                     <button type="submit" class="btn add-genre-btn">Add Genre</button>
                                 </div>
                             </form>
                         </div>
                     </div>
            </div>
        </div>
    </div>
    
{% endblock %}

application/templates/password-reset-email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Hello {{user}}</p>
    <p>Please follow <a href="{{url_for('users.reset_password', token=token, _external=True)}}">this link</a> to reset
        your password:</p>
    <p>Many thanks</p>
    <p>Cross//Tracks</p>
</body>
</html>

application/templates/reset-password.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col s12">
            <div class="reset-password-header center-align">
                 <h1>Reset Your Password</h1>
            </div>
            <div class="container">
                <div class="col s12 m6">
                    <form action="{{url_for('users.update_password')}}" method="POST">
                        <div class="input-field">
                            <input type="password" name="password" id="password" class="required-input" required>
                            <label for="password">Password</label>
                        </div>
                        <div class="input-field">
                            <input type="password" name="confirm_password" id="confirm_password" class="required-input" required>
                            <label for="confirm_password">Confirm Password</label>
                        </div>
                        <div class="submit-btn right-align">
                            <button type="submit" class="btn">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}